apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2021-05-17T16:08:09Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "46"
    selfLink: /api/v1/namespaces/default/services/kubernetes
    uid: 2babaf54-3467-44ef-8420-b2c8179c2929
  spec:
    clusterIP: 10.0.0.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2021-05-17T16:21:05Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: nginx
    name: my-service
    namespace: default
    resourceVersion: "2034"
    selfLink: /api/v1/namespaces/default/services/my-service
    uid: e9b21bda-ce22-4be3-aed0-8ae10e26323c
  spec:
    clusterIP: 10.0.77.207
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 32545
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 20.82.19.226
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
